sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pawanchoure/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pawanchoure/docker-react npm run test -- --coverage 